### ISSUE TITLE
/api/vendor

### ISSUE THREAD

**Issue by mIIwaukee** [waspeer/prophet08librarian#1]
Hi, What files need to go in here?

**Comment by mIIwaukee** [comment]
Got it

Open terminal
brew install composer
cd PATHTODIRECTORY/api/

composer require slim/slim "^3.0"

reload

**Comment by waspeer** [comment]
That folder is for the dependencies of the API. These have to be installed first with composer. I forgot to mention that in the README.

1. Go to the app-folder in the terminal (`cd path/to/app`)
2. Go to the api folder in the terminal (`cd api`)
3. Install dependencies (`composer install`)

If you don’t have composer installed, you can install it with [homebrew](https://brew.sh/) in the terminal: `brew install composer`.

I’ve added this in the README now. Thanks for pointing it out.

-- 
Wannes Salomé

Op 3 februari 2019 bij 15:58:56, Mark Roller (notifications@github.com) schreef:

Hi, What files need to go in here?
